name: "tagged-release"

on:
  push:
    branches:
      - "main"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: build
      run: cd /home/runner/work/mqx/mqx/app/mqxd && ../../scripts/gobuild.sh mqxd /mqxd
      shell: bash